"""
One-time (or one-time-per-source) interactive pairing helper for
opencpn_bridge.py. Run this directly:

    python3 pair_thor.py

It sends a deliberately short probe api_key (forcing OpenCPN's "old-style"
CompatHash branch, so the expected algorithm is known rather than whatever
this source's last attempt happened to leave it on - see config.py's
OPENCPN_* comment block for why that matters), asks you to read the 4-digit
pincode off OpenCPN's own screen on the Thor, computes the matching
api_key, and confirms it against /api/ping. Print the resulting
OPENCPN_API_KEY value at the end - put it in your environment (or a .env
this project's process loads) and every future opencpn_bridge.push_grib()
call just works, no more pincode dance.
"""

import sys

import requests
import urllib3

import config
from opencpn_bridge import compat_hash

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


def main():
    base_url = config.OPENCPN_REST_URL.rstrip("/")
    source = config.OPENCPN_SOURCE

    print(f"Pairing source={source!r} with OpenCPN at {base_url} ...")
    try:
        version = requests.get(f"{base_url}/api/get-version", timeout=10, verify=False).json()
    except Exception as e:
        print(f"Could not reach {base_url}/api/get-version at all: {e}")
        print("Check OPENCPN_REST_URL / that OpenCPN's REST server is running.")
        sys.exit(1)
    print(f"Reachable - OpenCPN version {version.get('version')}")

    print("\nSending a probe to trigger a fresh pincode dialog on OpenCPN's screen...")
    requests.get(
        f"{base_url}/api/ping", params={"source": source, "apikey": "0"}, timeout=10, verify=False
    )

    pincode = input("\nEnter the 4-digit pincode shown in OpenCPN's dialog on the Thor: ").strip()
    if not (pincode.isdigit() and len(pincode) == 4):
        print(f"'{pincode}' doesn't look like a 4-digit pincode - aborting.")
        sys.exit(1)

    api_key = compat_hash(int(pincode))
    print(f"\nComputed api_key = {api_key}")
    print("(It's fine to click OK/Cancel on the dialog now, or leave it - doesn't affect pairing.)")

    resp = requests.get(
        f"{base_url}/api/ping", params={"source": source, "apikey": api_key}, timeout=10, verify=False
    ).json()

    if resp.get("result") == 0:
        print(f"\nPaired successfully. Set this in your environment:\n\n    export OPENCPN_API_KEY={api_key}\n")
    else:
        print(f"\nStill not paired (result={resp.get('result')}). "
              "A new pincode was likely generated by this failed attempt - "
              "check OpenCPN's screen and rerun this script.")
        sys.exit(1)


if __name__ == "__main__":
    main()
